name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or your default branch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'  # specify the Node.js version if needed

      - name: Install dependencies
        run: |
          npm install
          
      - name: Build the project
        run: |
          # Add your build commands here, if needed
          # For example, if using Jekyll:
          # bundle exec jekyll build
          
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./  # Adjust this to the correct directory for your build output
